package com.lab.labtimesheet.platform.authorization;

/**
 * Stable keys for the 36 capabilities of Authorization §5.2. Their exact labels live only in the
 * catalogue resource, so shared code names no business-module concept.
 */
public enum AuthorizationCapability {
    MANAGE_ACCOUNTS,
    ACCOUNT_LIFECYCLE,
    GLOBAL_CONFIGURATION,
    VIEW_ALL_PROJECTS,
    CREATE_PROJECT,
    EDIT_PROJECT,
    DELETE_EMPTY_PLANNED_PROJECT,
    CANCEL_PROJECT,
    MANAGE_PROJECT_MEMBERS,
    PROJECT_INVITATIONS,
    MEMBERSHIP_EXIT,
    PROJECT_LEADERSHIP,
    REDISTRIBUTE_PENDING_EXIT_TASKS,
    CREATE_TASK,
    ASSIGN_TASK,
    TASK_ESTIMATE,
    REMAINING_EFFORT_FORECAST,
    EDIT_OR_DELETE_TASK,
    OWN_ASSIGNED_TASK_STATUS,
    BLOCK_UNBLOCK_REOPEN_TASK,
    START_ANOTHER_MEMBERS_TASK,
    COMMENT_ON_TASK,
    OWN_TASK_WORK_LOG,
    VIEW_AGGREGATE_PROJECT_PROGRESS,
    VIEW_PROJECT_TASK_HISTORY,
    VIEW_PER_MEMBER_PROJECT_HOURS,
    VIEW_INTERN_ATTENDANCE,
    DECIDE_ATTENDANCE_REQUEST,
    SUBMIT_ATTENDANCE_REQUEST,
    WITHDRAW_LEAVE_REQUEST,
    REQUEST_ATTENDANCE_PERIOD_REOPEN,
    DECIDE_ATTENDANCE_PERIOD_REOPEN,
    ATTENDANCE_REPORT,
    PROJECT_TASK_REPORT,
    DAILY_PROJECT_REPORT,
    OWN_ATTENDANCE_DATE;
}
