ALTER TABLE notifications
    DROP CONSTRAINT ck_notifications_type;

ALTER TABLE notifications
    ADD CONSTRAINT ck_notifications_type CHECK (
        notification_type IN (
            'LEAVE_SUBMITTED', 'LEAVE_DECIDED',
            'CORRECTION_SUBMITTED', 'CORRECTION_DECIDED',
            'ATTENDANCE_EXCEPTION_SUBMITTED', 'ATTENDANCE_EXCEPTION_DECIDED',
            'MEMBERSHIP_CHANGED', 'LEADERSHIP_CHANGED',
            'PROJECT_INVITATION_CREATED', 'PROJECT_INVITATION_RESOLVED',
            'MEMBERSHIP_EXIT_REQUESTED', 'MEMBERSHIP_EXIT_RESOLVED',
            'TASK_ASSIGNED', 'TASK_REASSIGNED',
            'TASK_STATUS_CHANGED', 'TASK_COMMENTED', 'SYSTEM'
        )
    );
